# https://golangci-lint.run/docs/configuration/file/
# https://github.com/golangci/golangci-lint/blob/HEAD/.golangci.reference.yml
# run: golangci-lint run
version: "2"

formatters:
  enable:
    - gofmt
    - goimports
    # - golines

  settings:
    # goimports:
    #   local-prefixes:
    #     - github.com/pacer/core
    golines: # https://golangci-lint.run/docs/formatters/configuration/#golines
      max-len: 90
      shorten-comments: true

linters:
  default: standard
  enable:
    - errorlint # error wrapping best practices
    - gocritic # opinionated but useful
    - misspell # spelling mistakes
    # modernize: disabled — go fix ./... applies the same analyzers (golang.org/x/tools/go/analysis/passes/modernize)
    - nilerr # returning nil after checking err != nil
    - unconvert # unnecessary type conversions
    - unparam # unused function parameters
    - whitespace # leading/trailing whitespace
    - gocheckcompilerdirectives
    - godoclint
    - gosec
    - importas
    # intrange: disabled — go fix ./... applies the same rangeint analyzer
    - perfsprint
    - usestdlibvars
  disable:
    - goconst
    - modernize # go fix ./... applies the same modernize analyzers
    - intrange # go fix ./... applies the same rangeint analyzer

  settings:
    gocritic: # https://go-critic.com/overview
      enabled-checks:
        - sqlQuery
        - boolExprSimplify
        - deferUnlambda
        - dupImport
        - emptyFallthrough
        - emptyStringTest
        - nestingReduce
        - paramTypeCombine
        - ptrToRefParam
        - stringConcatSimplify
        - typeUnparen
        - appendCombine
        # - hugeParam
        - preferFprint
        - preferStringWriter
        - rangeExprCopy
        - sliceClear
      disabled-checks:
        - ifElseChain # switch vs if-else is style preference
        - exitAfterDefer # sometimes intentional

  exclusions:
    rules:
      # CGO bridge file triggers false positives: dupImport (import "C"
      # must be separate) and dupSubExpr (CGO-generated expressions).
      - linters: [gocritic]
        path: internal/bridge/
      # CLI tool intentionally reads user-specified file paths.
      - linters: [gosec]
        text: "G304"
      # Test files writing to temp dirs don't need restrictive permissions.
      - linters: [gosec]
        text: "G306"
        path: _test\.go

    paths:
      - ".*\\.my\\.go$"
      - ".*\\.sql\\.go$" # sqlc-generated files
      - main.go
      - "^\\.claude/"
      - "^web/"
